import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  appContainer: {
    flex: 1,
    paddingTop: 50,
    paddingHorizontal: 20,
    // backgroundColor: '#EEF5FF',
    backgroundColor: '#000',
  },
  appHeading: {
    fontSize: 40,
    fontWeight: 'bold',
    marginTop: 10,
    // color: '#0F2167',
    color: '#fff',
  },
  appHeadingIntro: {
    fontSize: 20,
    fontWeight: 'bold',
    marginTop: 20,
    // color: '#0F2167',
    color: '#fff',
  },
  inputContainer: {
    // flex: 1,
    // flexDirection: 'row',
    // justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomColor: 'black',
    // borderBottomWidth: 2,
    padding: 20,
  },
  modalButtons: {
    marginRight: 50,
    marginLeft: 50,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  textInput: {
    borderWidth: 1,
    borderColor: '#fff',
    borderRadius: 10,
    width: '90%',
    marginRight: 8,
    padding: 10,
    color: '#fff',
  },
  goalList: {
    flex: 5,
    marginTop: 10,
    borderRadius: 6,
  },
  goal: {
    fontSize: 20,
    backgroundColor: '#176B87',
    padding: 10,
    color: '#fff',
    borderRadius: 10,
    marginBottom: 10,
  },
  goalText: {
    fontSize: 18,
    backgroundColor: '#176B87',
    color: '#fff',
  },
  goalHeading: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 10,
  },
  scrollView: {
    marginBottom: 100,
  },
  pressedStyle: {
    opacity: 0.5,
  },
  modalStyle: {
    padding: 10,
    marginTop: 15,
    marginBottom: 20,
    backgroundColor: '#000',
    borderRadius: 10,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#000',
    shadowColor: '#000000',
    shadowOffset: { width: 10, height: 5 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 5,
  },
  modalOpenStyle: {
    padding: 10,
    marginTop: 15,
    marginBottom: 20,
    backgroundColor: '#B4D4FF',
    borderRadius: 10,
  },
});
